version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_cnab
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: bancocnab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: